stages:
    - build
    - deploy

build_production:
    stage: build
    cache:
        key:
            files:
                - package-lock.json
        paths:
            - node_modules
    script:
        - echo "$DOCKER_PW" | docker login --username ctg96 --password-stdin
        - docker build -t ctg96/ctgjdw:health-check-proxy .
        - docker push ctg96/ctgjdw:health-check-proxy
    only:
        - master
    tags:
        - docker-shell
    
deploy_production:
    stage: deploy
    before_script:
        - apk add --no-cache openssh-client
        - mkdir -p ~/.ssh
        - echo "$SSH_KEY" > ~/.ssh/id_rsa
        - chmod 700 -R ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no $SSH_USER@$HOST -p $PORT "docker stop health-check-proxy && docker rm health-check-proxy && docker rmi ctg96/ctgjdw:health-check-proxy && docker run -d --name health-check-proxy -p 8081:8080 --restart always ctg96/ctgjdw:health-check-proxy"
    only:
        - master
    tags:
        - docker-1
